### ISSUE TITLE
Multiples pedidos creados en OpenCart

### ISSUE THREAD

**Issue by LuisCanal** [mercadopago/cart-opencart#10]
Al momento del checkout, utilizando el plugin se van creando muchos pedidos antes del pago final de la orden. Es decir por cada paso del checkout al parecer se crea un pedido diferente en opencart !!! Ayuda por favor  !!!

**Comment by falehenrique** [comment]
Hola por favor, actualize lo módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias.
