### ISSUE TITLE
Error MP en opencar 2.2.0.0

### ISSUE THREAD

**Issue by rafaelg21** [mercadopago/cart-opencart#100]
Buen dia saludos a todos, tengo una version de **Opencart v2.2.0.0** y una plantilla **Journal v2.9.4** y me descargue la ultima version del mercado pago realizando la instalación correspondiente a esa version, **v2.x - 2.2** el subdir **Standard** pero resulta que cuando voy hacer el pago me ejecuta este error ya cuando voy a confirmar 

Fatal error: Uncaught exception 'MercadoPagoException' with message 'error setting certificate verify locations: CAfile: /home/unicauchoslara/public_html/nueva/catalog/controller/payment/cacert.pem CApath: none' in /home/unicauchoslara/public_html/nueva/catalog/controller/payment/mercadopago.php:503 Stack trace: #0 /home/unicauchoslara/public_html/nueva/catalog/controller/payment/mercadopago.php(544): MPRestClient::exec(Array) #1 /home/unicauchoslara/public_html/nueva/catalog/controller/payment/mercadopago.php(58): MPRestClient::post(Array) #2 /home/unicauchoslara/public_html/nueva/catalog/controller/payment/mercadopago.php(236): MP->get_access_token() #3 /home/unicauchoslara/public_html/nueva/catalog/controller/payment/mp_standard.php(193): MP->create_preference(Array) #4 [internal function]: ControllerPaymentMPStandard->index(Array) #5 /home/unicauchoslara/public_html/nueva/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(44): call_user_func_array(Array, Array) #6 /home/unicauchoslara/public_ht in /home/unicauchoslara/public_html/nueva/catalog/controller/payment/mercadopago.php on line 503

Alguien tiene alguna idea del porque ejecuta ese error? Muchas Gracias y espero me puedan ayudar.

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)
