### ISSUE TITLE
Erro ao escolher o País

### ISSUE THREAD

**Issue by alcir-junior-caju** [mercadopago/cart-opencart#101]
Quando escolho o País ele não carrega as formas de pagamento, o seguinte erro aparece:

Uncaught TypeError: Cannot read property 'get' of undefined
    at HTMLSelectElement.country.onchange (mp_standard.js:14)
country.onchange @ mp_standard.js:14

**Comment by Guimoraes** [comment]
Estou com o mesmo problema. Há previsão de solução? V. 2.3.0.2

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)
