### ISSUE TITLE
Compatibilidad con Opencart 3.0

### ISSUE THREAD

**Issue by Tomicapo** [mercadopago/cart-opencart#107]
Hola. 
Tienen pensado un release para la versión 3.0? 
Para cuándo?
Saludos!

**Comment by dforce2055** [comment]
Me sumo a la consulta de @Tomicapo. ¿Para cuando una release para opencart 3.0?

**Comment by mjsorribas** [comment]
Me sumo a la consulta.Ya hace rato que esta la 3.x y cambio mucho la interfaz.  ¿Para cuando una release para opencart 3.0.x?

**Comment by trsistemas** [comment]
Me sumo a la consulta tambien...

**Comment by Tomicapo** [comment]
Hola. Novedades de esto?
Saludos y felices fiestas!

**Comment by Tomicapo** [comment]
Hola.
Alguien lee esto?
Saludos.

**Comment by john-urrutia** [comment]
Se tiene pensado soportar MercadoPago en la versión 3+ de Opencart?
La version 2.3 lleva al menos dos años sin commits en GitHub....

**Comment by flaviofat** [comment]
Hola a todos, disponibilizamos el nuevo plugin para Opencart 3.x en MKTP oficial de Opencart!
