### ISSUE TITLE
Método de pagamento bagunçado  

### ISSUE THREAD

**Issue by Antthony** [mercadopago/cart-opencart#108]
O módulo do MercadoPago está assim!
![image](https://user-images.githubusercontent.com/23645765/31024043-350015d6-a514-11e7-90db-464ec621685a.png)

https://prnt.sc/gr8bef

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)
