### ISSUE TITLE
Erro ao fechar o pedido

### ISSUE THREAD

**Issue by vidacalcados** [mercadopago/cart-opencart#11]
Ola bom dia, estou com o seguinte problema no modulo de pagamento.
Ao finalizar o pedido e clicar em retornar ao site do vendedor esta retorno o seguinte erro;

Notice: Undefined index: order_id in /home/vidacalc/public_html/catalog/controller/payment/mercadopago2.php on line 138Warning: Cannot modify header information - headers already sent by (output started at /home/vidacalc/public_html/index.php:106) in /home/vidacalc/public_html/vqmod/vqcache/vq2-system_engine_controller.php on line 28Warning: Cannot modify header information - headers already sent by (output started at /home/vidacalc/public_html/index.php:106) in /home/vidacalc/public_html/vqmod/vqcache/vq2-system_engine_controller.php on line 29

Observei que apos isso aconter, não gera o pedido no painel.

Algum sugestão de como resolver isso???
Aguardo e obrigado.

**Comment by falehenrique** [comment]
Olá, por favor atualize seu módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Obrigado.
