### ISSUE TITLE
Coupons not been discounted

### ISSUE THREAD

**Issue by rdmegna** [mercadopago/cart-opencart#110]
The coupons are not considered when the customers are redirected to mercado pago page.

I founded that if you comment this if case on lines 79-89, the coupons are considered correctly when the customer is redirected:
```

		$total = $this->currency->format($order_info['total'] - $this->cart->getSubTotal(), $order_info['currency_code'], false, false);

		if ($total > 0) { //custom code
			$items[] = array(
				"id" => 99,
				"title" => '',
				"description" => $this->language->get('text_total'),
				"quantity" => 1,
				"unit_price" => $total,
				"currency_id" => $currency,
				"category_id" => $this->config->get('mp_standard_category_id')
			);
		}
```
I'm not sure why there is this statement, it looks like it's supposed to prevent  some kind of fraud  but i think this is Opencart function.

**Comment by markhuizar** [comment]
I have the same problem, could you solved it?

**Comment by rdmegna** [comment]
Yes, i edited this file:

\catalog\controller\payment\mp_standard.php

I commented the line 77 and 89. Its a if statement.

**Comment by markhuizar** [comment]
You are the best. Thank you so much.
