### ISSUE TITLE
Permiso Denegado con Modulo de Mercado pago

### ISSUE THREAD

**Issue by naza1** [mercadopago/cart-opencart#117]
Version Opencart 2.0.3
Modulo de Mercado Pago: MercadoPago - Custom Checkout

Error:
![capture](https://user-images.githubusercontent.com/23777134/35306278-9f6fb3d2-007b-11e8-92b4-e53218eba63f.JPG)

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)
