### ISSUE TITLE
Error 500 al regresar a opencart

### ISSUE THREAD

**Issue by ericertl** [mercadopago/cart-opencart#118]
Luego de realizar el pago correctamente, al intentar hacer el redirect para volver a opencart, me da un error 500.

Este es un ej de la url que intenta usar: /index.php?route=payment/mp_standard/callback&collection_id=12587654&collection_status=approved&preference_id=116698725-0e95eb9a-7f91-4078-bd0a-22120c9e2076&external_reference=79&payment_type=account_money&merchant_order_id=null

Estimo que es porque merchant_order_id es null, aunque no se si esa sera la razon, o de porque ese valor es null.

Estoy usando oscommerce 2.2 y mercadopago standard

Otra cosa que note es que la opcion "Tipo de Checkout" no funciona. Por mas que ponga lightbox o iframe, siempre hace un redirect

**Comment by KEVAO28** [comment]
Tenho os mesmos problemas também, alguma solução ?

**Comment by ericertl** [comment]
Ninguna solucion, y por lo que se ve, no hay mucho mantenimiento de este repositorio.

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)
