### ISSUE TITLE
Erro ao ativar extensão - Opencart  2.3.0.2

### ISSUE THREAD

**Issue by eugeniots** [mercadopago/cart-opencart#126]
Fiz o download dos arquivos, subi para a raiz da instalação. 

Ativei em Extensões, fiz as configurações, porém ao clicar em finalizar carrinho apresenta o seguinte erro. 

Tanto para Custom Checkout ou Ticket Checkout

Fatal error: Cannot redeclare class MP in /home/inter183/public_html/eugenio/catalog/controller/extension/payment/lib/mercadopago.php on line 3

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)


Você não precisa copiar manualmente os arquivos, basta fazer o upload do mp.ocmod.zip

**Comment by eugeniots** [comment]
@flaviofat Perdão, mas sou novo por aqui e não entendi, a sua mensagem não tem vínculo com o que eu postei né? Pois uso a 2.3.0.2 e está falando da 3.x, correto?
