### ISSUE TITLE
error al configurar en back office opencart

### ISSUE THREAD

**Issue by nelsongn** [mercadopago/cart-opencart#13]
Warning: Cannot modify header information - headers already sent by (output started at /home/figucom/public_html/admin/language/spanish/payment/mercadopago2.php:1) in /home/figucom/public_html/vqmod/vqcache/vq2-system_engine_controller.php on line 28Warning: Cannot modify header information - headers already sent by (output started at /home/figucom/public_html/admin/language/spanish/payment/mercadopago2.php:1) in /home/figucom/public_html/vqmod/vqcache/vq2-system_engine_controller.php on line 29

**Comment by ghiamar** [comment]
Hola, se arregla usando el archivo de idioma en UTF-8, lo pueden tomar de este PR https://github.com/mercadopago/cart-opencart/pull/12/files
