### ISSUE TITLE
modulo para Opencart 2.0

### ISSUE THREAD

**Issue by nivelsur** [mercadopago/cart-opencart#17]
Hola Me gustaria saber si tienen pensado crear un modulo oficial para Opencart 2.0, seria muy bueno!

**Comment by tdra** [comment]
Misma pregunta, usaba el modulo pero acabo de actualizar a 2.0, y normalmente en mi sitio se realizan compras grandes

**Comment by mbove77** [comment]
Estamos esperando la versión para opencar 2 se puede colaborar con algo, soy programador?
Saludos.

**Comment by gLeW10** [comment]
Hola la misma consulta hay alguna novedad o tiene planeado hacerlo para la version 2.0 Gracias

**Comment by gebassetti** [comment]
+1 ¿Está en los planes?

**Comment by Mrtableta** [comment]
Alguna novedad?

**Comment by maxigsilva** [comment]
Buenas, los invito a visitar nuestra web! Disponemos del modulo de MercadoPago para las Versiones 2.x también probado en la versión 2.0.3.1. Esperamos sus comentarios y opiniones. Gracias.

**Comment by aledepaoli** [comment]
Estaría bueno saber si van a emitir una actualización para la versión 2.0. Gracias

**Comment by maxigsilva** [comment]
Hola, es totalmente compatible con todas las versiones 2.0. Saludos

**Comment by tdra** [comment]
maxigsilva hay una versión en Internet que es scam, esperamos a que vuelvan a retomar el proyecto para tener una oficial

**Comment by aledepaoli** [comment]
@maxigsilva acabo de instalar opencart 2.1 y con mercadopago no funciona. @tdra vos decís que la versión que ofrece taas.com.ar no sirve? Gracias

**Comment by tdra** [comment]
yo digo que hay una versión circulando que no sirve y que sólo es para estafar, la vi en la pagina de opencart en extensiones y muchos se quejaban de que era scam, no estoy diciendo que sea de ellos pero mejor vale prevenir que lamentar

**Comment by BartoGabriel** [comment]
+1

**Comment by migrania** [comment]
Buen día. Han conseguido hacer funcionar un modulo Mercadopago para opencart 2.2??..

**Comment by falehenrique** [comment]
Por favor, actualize lo módulo con la última versíon.

Gracias.
