### ISSUE TITLE
La moneda seleccionado no es aceptado por MercadoPago

### ISSUE THREAD

**Issue by juanmas07** [mercadopago/cart-opencart#23]
Hola, 
me sale el siguiente error

La moneda seleccionado no es aceptado por MercadoPago

El código de moneda que uso es ARS

**Comment by sebagun** [comment]
@juanmas07  ¿En qué país querés procesar pagos? ¿Con qué usuario?

**Comment by juanmas07** [comment]
en Argentina, mi email de MP es juanma_lace at hotmail.com

**Comment by mmalomo** [comment]
@juanmas07 pudiste solucionar el problema? a mi me pasa lo mismo

**Comment by arlyoneel** [comment]
Chequea que valor llega sobre la clase ControllerPaymentMercadopago2 en la línea que contiene:
"switch ($order_info['currency_code']) {"
por defecto si no tocaste la configuración de moneda en OC vas a obtener el valor USD

Vas a tener que agregar la moneda ARS si no está agregada y también ir a la tienda y cambiar el tipo de moneda por defecto.

Espero que les sirva, Namasté!

**Comment by mmalomo** [comment]
Encontré el problema de mi issue en particular. había realizado una orden de prueba que había quedado pendiente con una moneda que mercado pago no aceptaba. A pesar de no tener mas disponible esa moneda para realizar compras la orden había quedado asociada a esa moneda en particular. Asi que, borre la orden e hice una nueva y todo funciono correctamente.
Espero les sirva este dato.
