### ISSUE TITLE
Error al procesar pago

### ISSUE THREAD

**Issue by juanmas07** [mercadopago/cart-opencart#24]
Estoy usando opencart 1.5.6.4
Me está tirando los siguientes errores:

Command line: '/usr/sbin/apache2'
[Tue Sep 01 10:43:08.292029 2015] [core:crit] [pid 1696] (13)Permission denied: [client 127.0.0.1:54503] AH00529: /var/www/html/local/opencart/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/html/local/opencart/' is executable, referer: http://localhost/local/opencart/upload/admin/index.php?route=common/home&token=80ba42db8d2d51e92741ee5ef5e4c5dd

[Tue Sep 01 11:08:30.898800 2015] [:error] [pid 8338] [client 127.0.0.1:56717] PHP Fatal error:  Uncaught exception 'Exception' with message 'Empty reply from server' in /var/www/html/local/opencart/upload/catalog/controller/payment/mercadopago.php:399\nStack trace:\n#0 /var/www/html/local/opencart/upload/catalog/controller/payment/mercadopago.php(432): MPRestClient::exec('POST', '/checkout/prefe...', Array, 'application/jso...')\n#1 /var/www/html/local/opencart/upload/catalog/controller/payment/mercadopago.php(177): MPRestClient::post('/checkout/prefe...', Array)\n#2 /var/www/html/local/opencart/upload/catalog/controller/payment/mercadopago2.php(203): MP->create_preference(Array)\n#3 /var/www/html/local/opencart/upload/system/engine/controller.php(43): ControllerPaymentMercadopago2->index(Array)\n#4 /var/www/html/local/opencart/upload/catalog/controller/checkout/confirm.php(416): Controller->getChild('payment/mercado...')\n#5 [internal function]: ControllerCheckoutConfirm->index()\n#6 /var/www/html/local/opencart/upload/system/engine/front.php(42): call_user_func_array(Array, Array)\n#7 /var/www/html/local/openc in /var/www/html/local/opencart/upload/catalog/controller/payment/mercadopago.php on line 399, referer: http://localhost/local/opencart/upload/index.php?route=checkout/checkout

**Comment by BrunoCodeman** [comment]
@juanmas07 Este error indica que tu problema es en la instalación de PHP y Apache.

**Comment by martinsimondi** [comment]
a mi me tira un error con la nueva instalacion de opencart 2.1.0 como si no cargara el select de paises , categorias, un problema con el curl?? esta seria la funcion
private function callJson
