### ISSUE TITLE
MercadoEnvio

### ISSUE THREAD

**Issue by mbove77** [mercadopago/cart-opencart#25]
Se sabe si van a implementar la funcionalidad de MercadoEnvios pronto?

**Comment by BrunoCodeman** [comment]
@mbove77 Vamos tener la funcionalidad, pero aún no esta listo.

**Comment by ninamarth** [comment]
¿Todavía no hay noticias de MercadoEnvíos?

**Comment by josensanchez** [comment]
Hola, tienen pensado lanzar esta funcionalidad en algun momento de este año?

**Comment by josensanchez** [comment]
Porque esta cerrado este ticket?

**Comment by lcrangel** [comment]
ya estamos a 2017 aun no sale?

**Comment by juanma386** [comment]
¿Al final se ponen las pilas el 2019 o van a seguir jugando a los programadores?
