### ISSUE TITLE
Problema no Pagamento do frete

### ISSUE THREAD

**Issue by epdsantos** [mercadopago/cart-opencart#30]
O módulo funciona 99%. Finalizei uma compra e foi pago no mercado pago. Porém, na finalização da do pagamento, no MERCADOPAGO, não inclui o valor do frete para pagamento. É cobrado somente o valor do produto.
![mercadopago](https://cloud.githubusercontent.com/assets/5647706/12302475/8638e990-ba0c-11e5-83fc-a7a48f4e4d10.jpg)

**Comment by BrunoCodeman** [comment]
Bom dia. Qual a versão do OC utilizado?

**Comment by epdsantos** [comment]
Opencart 2.0.3.1.
Tema default.

**Comment by BrunoCodeman** [comment]
Qual o tipo de frete selecionado?

**Comment by epdsantos** [comment]
Sedex, correios, conforme a imagem.

**Comment by BrunoCodeman** [comment]
@epdsantos Módulo dos correios para prestashop?

**Comment by epdsantos** [comment]
Módulo de correios para Opencart.

**Comment by BrunoCodeman** [comment]
@epdsantos Existem 34 módulos de integração com os correios para OpenCart (http://www.opencart.com/index.php?route=extension/extension&filter_search=correios). Poderias por favor me informar qual está sendo utilizado?

**Comment by epdsantos** [comment]
@BrunoCodeman  Uso este: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=980&filter_search=correios&filter_license=0&filter_download_id=41

**Comment by BrunoCodeman** [comment]
@epdsantos obrigado, vou verificar o módulo e ver o que está ocorrendo.

**Comment by joaovieiraandrade** [comment]
@BrunoCodeman Agora pulei pra esse tópico também kkk. No teste que fiz do pagamento, no caso realizei o teste com o frete fixo, sem módulo de frete e também cobrou apenas o produto.

**Comment by sapo100** [comment]
Buen dia. Lo mismo sucede para el cargo de impuestos, el módulo está utilizando el subtotal. ¿Es posible utilizar mercadopago para varios productos en una misma transacción?. Saludos.

**Comment by BrunoCodeman** [comment]
@sapo100 Hola!  Si, es posible utilizar el modulo para varios productos en una misma transaccion, sin problemas.

**Comment by tulioreis27** [comment]
O problema foi resolvido já?

**Comment by tulioreis27** [comment]
@BrunoCodeman desculpa te encher o saco. Você conseguiu resolver?

**Comment by BrunoCodeman** [comment]
@tulioreis27 Eu é que peço desculpas pela demora, entendo perfeitamente que a pergunta está sendo feita por uma questão de necessidade da tua parte. Acredito que amanhã ao final do dia eu já libere a correção desse e de mais alguns bugs.

**Comment by tulioreis27** [comment]
@BrunoCodeman Muito obrigado pela atenção. Fico no aguardo.

**Comment by mfpatta** [comment]
Estou tendo o mesmo problema, uso a versao 2.0.3.1, e na tela de pagamento do mercado pago, o valor do frete nao está sendo enviado junto com o valor do produto. Acabei de instalar o módulo, e o problema não é com o módulo dos correios, pois tenho outro meio de pagamento e ta funcionando corretamente.

**Comment by joaovieiraandrade** [comment]
@BrunoCodeman Acabei de fazer o teste aqui e agora puxou o valor do frete, perfeito! Estou usando o mesmo módulo que o @epdsantos (link: http://goo.gl/rzNijL).
![frete-exemplo](https://cloud.githubusercontent.com/assets/16733768/12719018/a08dd342-c8d9-11e5-851b-d2b09c0cdc3e.jpg)

**Comment by joaovieiraandrade** [comment]
@BrunoCodeman Só mais um detalhe, percebi que meu opencart começou a dar um erro ao salvar qualquer módulo que tenha que escolher a posição. No caso do mercado pago eu não consigo escolher posição, então toda vez que acesso o módulo e clico em salvar ele da o erro, conhece alguma solução?
![sort_order](https://cloud.githubusercontent.com/assets/16733768/12719091/134d43f4-c8da-11e5-9da3-f294a3e4e042.jpg)

**Comment by BrunoCodeman** [comment]
@joaovieiraandrade corrigi isso agora

**Comment by joaovieiraandrade** [comment]
Beleza @BrunoCodeman, esse erro de sort_order resolveu, mas quando tento salvar ainda persistem esses erros:
![undefined-index](https://cloud.githubusercontent.com/assets/16733768/12722333/97602e84-c8eb-11e5-940a-638ca2057eca.jpg)
Na linha **274** do arquivo **mercadopago2.php** percebi que estava sem **!** no comando **if (!$this->**, mas editei e não resolveu.

**Comment by mfpatta** [comment]
No meu caso nao deu, atualizei a versão do meu módulo dos correios para o indicado pelo @BrunoCodeman mas continuou a mesma coisa.

**Comment by BrunoCodeman** [comment]
@mfpatta @joaovieiraandrade acabei de enviar o pull request para o repositório.

**Comment by joaovieiraandrade** [comment]
Caramba, por mim poderia fechar o tópico rsrs! Parabéns @BrunoCodeman, está rodando perfeitamente agora!

**Comment by mfpatta** [comment]
@BrunoCodeman, qual o de Tipo de Checkout voce está usando?

**Comment by BrunoCodeman** [comment]
@joaovieiraandrade Obrigado! Estamos aqui pra isso, hehe. ;)

**Comment by BrunoCodeman** [comment]
@mfpatta Sempre executo testes nos 3 tipos. Estás tendo problemas com algum deles?

**Comment by mfpatta** [comment]
Testei em todos eles, mas continuo com o problema de não puxar o valor do frete,

**Comment by joaovieiraandrade** [comment]
@mfpatta Os testes que fiz foram assim, copiei todos os arquivos da pasta v2.x para a raiz da loja e sobrescrevi todos os arquivos que já estavam lá, depois acessei o menu Extensões -> Modificações e cliquei em atualizar. Após isso o módulo funcionou perfeitamente. Você sempre atualiza os módulos quando copia os novos arquivos?

**Comment by tulioreis27** [comment]
@joaovieiraandrade  me tire um duvida. Se eu fizer download dos aquivos agora, terei que fazer todas as correções ou eles já estão corrigidos?

**Comment by joaovieiraandrade** [comment]
Olá @tulioreis27, já estão com todas as correções. Faz o download de toda a pasta v2.x e copia todos os arquivos pro seu servidor, caso já tenha o módulo instalado, substitua todos os arquivos, depois faça esse procedimento de atualizar que falei acima.
Dessa forma deve rodar sem problemas.

**Comment by BrunoCodeman** [comment]
@tulioreis27 Conseguiste fazer a atualização com as dicas do @joaovieiraandrade?

**Comment by tulioreis27** [comment]
@BrunoCodeman eu não estava conseguindo pois estava testando no servidor local. Mas agora coloquei no meu servidor e funcionou perfeitamente. Muito show cara. Agora tem até Checkout Transparente.

**Comment by BrunoCodeman** [comment]
@tulioreis27 O checkout transparente "escapou" por uma desatenção minha, ainda não está pronto. Mas ficou feliz que agora tenha funcionado. :)

**Comment by mfpatta** [comment]
Po, devo ta com azar mesmo, fiz como voce disse @joaovieiraandrade e nada, isso que to usando o template padrao, to vendo que vou ter que remover todos os arquivos, e começar do inicio de novo.

**Comment by joaovieiraandrade** [comment]
@mfpatta Você viu que o @tulioreis27 estava com problemas também porque estava usando o servidor local, você está com hospedagem online ou está fazendo testes na sua maquina?
Antes de você apagar tudo do seu servidor, cria uma nova pasta na raiz da sua hospedagem e um banco de dados novo, depois faz uma instalação limpa do opencode dentro dessa pasta, pra você testar o módulo.

**Comment by mfpatta** [comment]
@joaovieiraandrade eu vi, mas estou rodando o site em um servidor online, o site ja tudo funcionando, só nao funciona corretamente o modulo do mercado pago, tenho do pagseguro e correios (indicado acima) funcionando.

**Comment by joaovieiraandrade** [comment]
Então tenta fazer dessa forma @mfpatta, cria uma pasta dentro do seu site com nome de "teste", depois jogo os arquivos do opencart dentro dela e faz a instalação. Lembra de criar também uma base de dados nova, pode ser com nome de teste também, só pra não misturar com a da sua loja. Dessa forma você vai saber se é algum conflito com arquivos de outros módulos.

**Comment by joaovieiraandrade** [comment]
@mfpatta Conseguiu fazer funcionar?

**Comment by mfpatta** [comment]
Olá @joaovieiraandrade então, não consegui resolver, eu nao entendo muito de criar base de dados e fazer como voce falou, mas estou vendo com um webmaster, se resolvemos, mas até agora nada.

**Comment by joaovieiraandrade** [comment]
Beleza @mfpatta, mas foi você que fez a instalação do opencart no servidor?

**Comment by mfpatta** [comment]
@joaovieiraandrade fiz o seguinte, no Cpanel do meu servidor bysite, tem um instalador automático chamado softaculous, fiz a instação do opencart por ele, tudo automatico, só configurei, o site está no ar, com template padrao, tá rodando o pagseguro e bcash normalmente, alem dos correios.

**Comment by joaovieiraandrade** [comment]
Entendi, é muito simples pra instalar o opencart manualmente, mas se conseguir criar um usuario ftp e me passar posso deixar os arquivos no jeito pra você concluir a instalação.

**Comment by mfpatta** [comment]
@joaovieiraandrade mas voce quer fazer uma nova instalação do OC? sinceramente nao to afim de configurar ou ajustar tudo novamente só por causa do MP. Outra coisa, quando faço uma instalação pelo Softaculous, é posso fazer uma atualização, sempre que lança uma nova versão da plataforma, só clicando em um botão.

**Comment by joaovieiraandrade** [comment]
@mfpatta Nesse caso fica a seu critério, eu preciso do MP pois já trabalho com vendas pelo Mercado Livre, dessa forma teremos uma conta virtual com todo o caixa da loja, tanto no site como no ML. Se você ainda não usa o MP e já tem outros dois meios de pagamentos rodando é melhor ficar neles mesmo do que quebrar a cabeça com um novo.
