### ISSUE TITLE
Botão salvar não funciona / Save button doesn't work

### ISSUE THREAD

**Issue by joaovieiraandrade** [mercadopago/cart-opencart#31]
Galera, estou usando o Opencart 2.1.0.2 e instalei o módulo perfeitamente. O problema está na hora de habilitar o módulo, faço todas as configurações mas quando clico em salvar simplesmente não acontece nada.
Alguém com o mesmo problema?
-----------------------------------------------------------------------------
I'm using OpenCart 2.1.0.2 and the module was installed perfectly. The problem is when I try to enable the module, do all settings but when I click save nothing happens.
Someone with the same problem?

**Comment by samxd17** [comment]
Same problem here.
I'm trying installing others versions of opencart.
Tried 2.0.1.1 and 2.0.2.0 and the same problem... clicking on "Save" nothing happens.
I'm installing right now opencart 2.0.3.1 ...  to try

Maybe 2.0.0.0? 
I'm frustrated

Help!!! :(

**Comment by BrunoCodeman** [comment]
Did you tried to save, leave the page and enter again to check if the configuration was saved?

**Comment by samxd17** [comment]
Yes. if I click save, and leave the page and enter again to check. all the fields are empty.

**Comment by samxd17** [comment]
tryed opencart 2.0.3.1. same problem.

**Comment by joaovieiraandrade** [comment]
When I go out and come in again on the page, all settings are lost. I have tested different browsers, same problem.

**Comment by joaovieiraandrade** [comment]
Only the button Cancel works fine...

**Comment by BrunoCodeman** [comment]
Can you inform me the operating system you're using, please?

**Comment by joaovieiraandrade** [comment]
Windows 10, I'll try in the win7...

**Comment by joaovieiraandrade** [comment]
Same problem on Win7 and Server 2008

**Comment by BrunoCodeman** [comment]
I've made some modifications and pushed them a few minutes ago. Can you please check if  commit d141c4db5d8b2be5b8873f9f0e1cb64e68868982 solved the problem for you? Thanks. :)

**Comment by joaovieiraandrade** [comment]
Now the save button refreshes the page, but the methods of payments that would be for Brazil, turn to the methods of Argentina and loses all selection.

Thaks for the support BrunoCodeman!

**Comment by JohnKurt** [comment]
Olá João Vieira, boa noite!

Você esta online meu amigo..

Estou com um pequeno problema na instalação do meu opencart-2.1.0.1  em meu
servidor, você poderia me ajudar a subir os

Arquivos para o diretório Raiz

A equipe suporte desconhece o problema, mas tem uma pasta no diretório como
o nome php.ini com a mesma extensão do php.ini do opencart-2.1.0.1 .

Será este o problema?

Se poder me ajudar eu lhe agradeço.

Vou lhe enviar  a minha senha FTP caso você tenha interesse em me ajudar..

Obrigado pelo seu tempo e tenha os meus melhores cumprimentos.

At:

Edson Gomes

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Hello Joao Vieira, good night!

You are my friend online ..

I have a little problem installing my opencart-2.1.0.1 on my server, you
could help me up the

Files to the root directory

The support team is unaware of the problem, but have a folder in the
directory as the name php.ini with the same php.ini extension of
opencart-2.1.0.1.

Is this the problem?

If you can help me I thank you.

I will send you my FTP password if you are interested in helping me ..

Thanks for your time and do my best regards.

At:

Edson Gomes

2016-01-18 16:29 GMT-02:00 João Vieira <notifications@github.com>:

> Now the save button refreshes the page, but the methods of payments that
> would be for Brazil, turn to the methods of Argentina and loses all
> selection.
>
> Thaks for the support BrunoCodeman!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mercadopago/cart-opencart/issues/31#issuecomment-172614871>
> .
>



-- 

Desde já Agradeço
Edson Gomes

**Comment by JohnKurt** [comment]
Olá João Vieira, boa noite!
Você esta online meu amigo..
Estou com um pequeno problema na instalação do meu opencart-2.1.0.1  em meu servidor, você poderia me ajudar a subir os
Arquivos para o diretório Raiz
A equipe suporte desconhece o problema, mas tem uma pasta no diretório como o nome php.ini com a mesma extensão do php.ini do opencart-2.1.0.1 .
Será este o problema?
Se poder me ajudar eu lhe agradeço.
Vou lhe enviar  a minha senha FTP caso você tenha interesse em me ajudar..
Obrigado pelo seu tempo e tenha os meus melhores cumprimentos.
At:
Edson Gomes

**Comment by samxd17** [comment]
tested with version 2.0.3.1 on Windows 7.
now it works. thank you very much BrunoCodeman!!.
one detail: when the button is pressed "save", the page remains in the same place. you have to close that page, but changes are preserved. Now MercadoPago is active in my store. Now I'm going to do a test to verify the payment. :)

**Comment by joaovieiraandrade** [comment]
I tested with versions 2.1.0.2, 2.1.0.1 and 2.0.1.3, in all the page refreshes, but the settings are not saved. I've tried to close the page and return, but it did work.
Every time I did a clean install of opencart.

**Comment by BrunoCodeman** [comment]
@joaovieiraandrade is curl installed in your windows?

**Comment by BrunoCodeman** [comment]
@samxd17 Good to know it's working now. :)

I'm working on the notifications and return messages to users, I'll make it more friendly. :)

**Comment by joaovieiraandrade** [comment]
@BrunoCodeman, the site is hosted on a server Hostgator, but I'm using Windows 10. I did also test a browser in Windows 7, but made no difference.

**Comment by joaovieiraandrade** [comment]
I did a test installation, take a look:

www.motocrossourinhos.com/teste/admin
user:**admin**
pass:**admin**

**Comment by joaovieiraandrade** [comment]
Nenhuma novidade @BrunoCodeman ?

**Comment by BrunoCodeman** [comment]
@joaovieiraandrade fiz o teste e os dados estão salvos lá.

**Comment by joaovieiraandrade** [comment]
@BrunoCodeman Realmente está funcionando agora, acabei de fazer o teste na loja mesmo e salvou perfeitamente. Agora vou fazer alguns teste com o pagamento.
Muito obrigado pela força Bruno!

**Comment by BrunoCodeman** [comment]
@joaovieiraandrade disponha, João. :)

**Comment by BrunoCodeman** [comment]
@joaovieiraandrade fiz mais commits, corrigindo alguns bugs: https://github.com/BrunoCodeman/cart-opencart
