### ISSUE TITLE
Erro ao configurar o MercadoPago

### ISSUE THREAD

**Issue by MarksEliel** [mercadopago/cart-opencart#33]
1- Não aparece nenhuma categoria.

2- Warning: Invalid argument supplied for foreach() in C:\wamp\www\opencart\admin\view\template\payment\mercadopago2.tpl on line 214

**Comment by BrunoCodeman** [comment]
@MarksEliel qual a versão do Windows utilizada?

**Comment by MarksEliel** [comment]
Estou usando Windows 7, mais tem alguma coisa haver com o módulo? já que estou rodando em servidor local?

**Comment by BrunoCodeman** [comment]
@MarksEliel pergunto por que um dos nossos desenvolvedores teve problemas ao executar o PrestaShop com alguns módulos no Windows. Como foi necessário até reconfigurar o PHP.ini, sempre checo se pode ser um erro semelhante.

**Comment by trsistemas** [comment]
Tenho o mesmo problema e nao estou conseguindo resolve-lo...

**Comment by trsistemas** [comment]
Perdao, ao dar erro da categoria e do resto das opcoes q busca no ML   
2016-01-28 23:27:22 - PHP Warning:  Invalid argument supplied for foreach() in /www/cli14754/htdocs/admin/view/template/payment/mercadopago2.tpl on line 86
2016-01-28 23:27:22 - PHP Warning:  Invalid argument supplied for foreach() in /www/cli14754/htdocs/admin/view/template/payment/mercadopago2.tpl on line 180
2016-01-28 23:27:22 - PHP Warning:  Invalid argument supplied for foreach() in /www/cli14754/htdocs/admin/view/template/payment/mercadopago2.tpl on line 214

**Comment by BrunoCodeman** [comment]
@MarksEliel @trsistemas Hoje até a noite devemos ter uma versão nova do módulo que já corrige esse problema.

**Comment by carlosamallo** [comment]
Hi! i have the same problem, i cant setup. 
Options category and country store are not displayed and this error appear:
`Warning: Invalid argument supplied for foreach() in /www/tiendapixeles/htdocs/admin/view/template/payment/mercadopago2.tpl on line `214``

![error opencart](https://cloud.githubusercontent.com/assets/16994752/12706081/a1e2b6aa-c85b-11e5-8f41-83c9520c7be6.jpg)

**Comment by BrunoCodeman** [comment]
@carlosamallo 
Can you please try the new commited version? 
https://github.com/mercadopago/cart-opencart/pull/34

**Comment by trsistemas** [comment]
Instalei a nova versao...
2016-02-01 17:04:36 - PHP Warning:  Invalid argument supplied for foreach() in /www/cli14754/htdocs/admin/controller/payment/mercadopago2.php on line 141
2016-02-01 17:04:36 - PHP Notice:  Undefined index: methods in /www/cli14754/htdocs/admin/controller/payment/mercadopago2.php on line 146
2016-02-01 17:04:36 - PHP Warning:  Invalid argument supplied for foreach() in /www/cli14754/htdocs/admin/view/template/payment/mercadopago2.tpl on line 104
2016-02-01 17:04:36 - PHP Warning:  Invalid argument supplied for foreach() in /www/cli14754/htdocs/admin/view/template/payment/mercadopago2.tpl on line 201

**Comment by BrunoCodeman** [comment]
@trsistemas e @MarksEliel, aqui como resolver o problema: https://github.com/mercadopago/cart-opencart/issues/35#issuecomment-179372442

**Comment by MarksEliel** [comment]
Outro erro:
Warning: Invalid argument supplied for foreach() in C:\wamp\www\opencart\admin\controller\payment\mercadopago2.php on line 141Notice: Undefined index: methods in C:\wamp\www\opencart\admin\controller\payment\mercadopago2.php on line 146

**Comment by BrunoCodeman** [comment]
@MarksEliel fizeste o procedimento do cURL que indiquei?

**Comment by migrania** [comment]
Buen día. Han podido solucionar el problema. No logro hacerlo funcionar. Ayuda!

**Comment by BrunoCodeman** [comment]
@migrania Hola, cual problema tienes?

**Comment by migrania** [comment]
Hola @BrunoCodeman gracias por contestar.
Tengo win7.. trabajo con firefox sobre opencart 2.2 desde el servidor (no local) y no logro configurar el modulo de pago "standard" de Mercadopago ya que no aparecen categorías. Me sale este error:
Warning: Invalid argument supplied for foreach() in /www/www.graphicshop.com.ar/htdocs/admin/controller/payment/mercadopago2.php on line 141
Te dejo una cap
![snap1](https://cloud.githubusercontent.com/assets/19335467/15262262/9417a512-1937-11e6-80f6-672d70cf39c5.jpg)

**Comment by BrunoCodeman** [comment]
@migrania Tienes SSH configurado en tu servidor?

**Comment by migrania** [comment]
@BrunoCodeman  ..ya mismo me fijo

**Comment by migrania** [comment]
@BrunoCodeman  ..no. lo activo?

**Comment by BrunoCodeman** [comment]
@migrania Cómo hiciste para fijarlo? Si, es necesario utilizar SSH. Todas las requisiciones que los modulos hacen a la API de MercadoPago son por HTTPS.

**Comment by migrania** [comment]
@BrunoCodeman  
![snap3](https://cloud.githubusercontent.com/assets/19335467/15262593/dabcfd08-1939-11e6-8918-6886070a4d71.jpg)
SSH tengo.... lo que no tengo instalado en el server es SSL

**Comment by BrunoCodeman** [comment]
Si, perdoname por mi error. Yo quise decir SSL, no SSH.

**Comment by migrania** [comment]
@BrunoCodeman  Ahh!... pensé que no necesitaba SSL. ¿sabes si con eso se me solucionará el problema?. Es que vi un módulo de pago en la tienda opencart que no necesita SSL

**Comment by BrunoCodeman** [comment]
@migrania Yo tengo el certificado SSL aquí y utilizo todos los modulos OpenCart sin errores. Creo que sea la solución.

**Comment by migrania** [comment]
@BrunoCodeman  Gracias maestro!.. acabo de comprar el certificado y en breve lo van a estar añadiendo a mi dominio.
Espero poder consultarte por cualquier otro inconveniente si es que aparece. Saludos!

**Comment by BrunoCodeman** [comment]
@migrania Por nada! Siempre que tengas dificultades con nuestro modulo OpenCart, estamos disponibles para ayudar!

**Comment by migrania** [comment]
Hola @BrunoCodeman. Siguiendo tu indicaciones de el otro día, compre el certificado SSL y con pocas modificaciones conseguí hacer funcionar el módulo mercadopago. Ahora te consulto ¿sabes porque no se ven las imagenes de sitio en ssl?. Saludos!

**Comment by dirsis** [comment]
necesito ayuda me da este error cuando quiero editar el modulo de mercadopago
Notice: Undefined index: token in /home/dirsis/public_html/shop/admin/controller/extension/payment/mp_transparente.php on line 60Notice: Undefined index: token in /home/dirsis/public_html/shop/admin/controller/extension/payment/mp_transparente.php on line 65Notice: Undefined index: token in /home/dirsis/public_html/shop/admin/controller/extension/payment/mp_transparente.php on line 70Notice: Undefined index: token in /home/dirsis/public_html/shop/admin/controller/extension/payment/mp_transparente.php on line 73Notice: Undefined index: token in /home/dirsis/public_html/shop/admin/controller/extension/payment/mp_transparente.php on line 74
tengo ssl, pero no se que puede ser???
