### ISSUE TITLE
Error Opencart 2x MercadoPago

### ISSUE THREAD

**Issue by carlosamallo** [mercadopago/cart-opencart#35]
Hi i cant setup. Options category and country store are not displayed and this error appear:
`Warning: Invalid argument supplied for foreach() in /www/tiendapixeles/htdocs/admin/view/template/payment/mercadopago2.tpl on line `214``

![error opencart](https://cloud.githubusercontent.com/assets/16994752/12706081/a1e2b6aa-c85b-11e5-8f41-83c9520c7be6.jpg)

**Comment by BrunoCodeman** [comment]
@carlosamallo fixed: https://github.com/BrunoCodeman/cart-opencart

**Comment by carlosamallo** [comment]
Hi Bruno! Thanks, other error happend and Options category and country are not displayed yet.

The error
`Warning: Invalid argument supplied for foreach() in /www/tiendapixeles/htdocs/admin/controller/payment/mercadopago2.php on line 141Notice: Undefined index: methods in /www/tiendapixeles/htdocs/admin/controller/payment/mercadopago2.php on line 146`
![error 7](https://cloud.githubusercontent.com/assets/16994752/12729678/af01ab7e-c906-11e5-909e-e52ee3adf917.png)

**Comment by vilsongabriel** [comment]
Quick fix:

in **admin/controller/payment/mercadopago2.php** find `$ch = curl_init();` _(line 203)_ and add after:
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

**Comment by BrunoCodeman** [comment]
@vilsongabriel thanks for the tip!

@carlosamallo probably your server or local machine is blocking the request to MercadoPago API that populate these fields.

**Comment by BrunoCodeman** [comment]
@carlosamallo One of my team members told me he had the same problem, but using Prestashop. To fix the problem, do the following:

1)Download a certificate at http://curl.haxx.se/docs/caextract.html

2)Add the following line to the [curl] session of your PHP.ini file:

curl.cainfo=/path/to/your/certificate

**Comment by carlosamallo** [comment]
Thanks @BrunoCodeman @vilsongabriel  
The situation now is: No error message appears on the admin. I can configure categories, regional and payment options. But .. when I go to do a trial run in the store, an error when confirming the payment appears asking me the certificate SSL. You Work hard and I am grateful for their efforts. Unfortunately I did not know that this module only works if the site has SSL certification. Alternative to using MercadoPago without certification?
I Attached error message.
![new error](https://cloud.githubusercontent.com/assets/16994752/12795486/2623485a-ca99-11e5-9981-017e1c6b7376.jpg)

**Comment by BrunoCodeman** [comment]
@carlosamallo Carlos, did you configured the curl certificate or used the quickfix?

**Comment by MarksEliel** [comment]
Outro Erro:
Warning: Invalid argument supplied for foreach() in C:\wamp\www\opencart\admin\controller\payment\mercadopago2.php on line 141Notice: Undefined index: methods in C:\wamp\www\opencart\admin\controller\payment\mercadopago2.php on line 146

**Comment by vilsongabriel** [comment]
@MarksEliel Use the quickfix, you also need to use it on the catalog controller.

**Comment by vilsongabriel** [comment]
@BrunoCodeman Apply the quickfix in the catalog controller too.

**Comment by carlosamallo** [comment]
@BrunoCodeman i configured the quickfix wich fix error in admin page. 
About the Curl certificate, I copied the text of the cert page, I created the file (certificate.pem), uploaded it to the root directory . And I added the line of code to php.ini and do not take me . If you say it should work , where do you think is wrong?

**Comment by BrunoCodeman** [comment]
@MarksEliel O problema citado aparentemente é de SSL. Fizeste a configuração do cURL que eu indiquei acima?

**Comment by BrunoCodeman** [comment]
@carlosamallo are you having the same error?

**Comment by carlosamallo** [comment]
@BrunoCodeman Apparently yes .

**Comment by BrunoCodeman** [comment]
@carlosamallo Carlos, what I see in your print is that you have an error in your certificate. That's what the error message says.

**Comment by Misterio182** [comment]
Hi everyone, I have installed Mercado Pago for Opencart Version 2.0.2 and I Had the same problem with the category box. I solved with the process that @vilsongabriel said: 
Quick fix:
in admin/controller/payment/mercadopago 2.php find $ch = curl_init(); (line 203) and add after:
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
but now other problem emerge, when I try to make a buying test something happend.

When I arrive to "Confirm Payment" section, the page display the next error with an a php table:

Warning: Invalid argument supplied for foreach() in C:\wamp64\www\opencart\catalog\controller\payment\mercadopago2.php on line 179
( ! ) Fatal error: Uncaught exception 'Exception' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\wamp64\www\opencart\catalog\controller\payment\mercadopago.php on line 425
( ! ) Exception: SSL certificate problem: unable to get local issuer certificate in C:\wamp64\www\opencart\catalog\controller\payment\mercadopago.php on line 425

I´m Working with Windows 7 x64 bits, and wampserver 3.0 PHP V5.6

I read in internet than I need to enable one PHP Extension called PHP_Curl what it is enabled.

@vilsongabriel you said that I need to use the quick fix in the catalog folder but... in the catalog folder in mercadopago.php I don´t found  $ch = curl_init() and I don´t found where put the: curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

I´m not an expert (I´m a noob :/ in all of this themes (also in english how you can see (coff coff google translate coff coff) ) 

Can anybody helpme? 

![table](https://cloud.githubusercontent.com/assets/18581534/14687995/ceaa3260-0705-11e6-82ce-34420b2f7b51.jpg)

**Comment by BrunoCodeman** [comment]
Hi @Misterio182,

you cannot disable SSL because all the calls to MercadoPago API are via SSL.

**Comment by Misterio182** [comment]
SOLVED:

Searching in the folder: catalog\controller\payment I found 2 Mercadopago php files, one called mercadopago2 and mercadopago so... what you have to do??

Step 1 (like a pro B|  xD ):

Open Mercadopago2.php and edit it, in the line 334 I found the "$ch = curl_init();"  then in the line 335  I follow the Quick Fix by @vilsongabriel : curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

save and close the file.

Step 2 (still an error and this will fix it): Open and edit Mercadopago.php in the line 382 you will find this: private static function get_connect($uri, $method, $content_type) {

then in the line 390 in the end type "intro" of have one space and paste again the Quick Fix: curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);  I put this in the line 391 and it work for me :)

you should have something like this:

private static function get_connect($uri, $method, $content_type) {
        if (!extension_loaded ("curl")) {
            throw new Exception("cURL extension not found. You need to enable cURL in your php.ini or another configuration you have.");
        }

        $connect = curl_init(self::API_BASE_URL . $uri);

        curl_setopt($connect, CURLOPT_USERAGENT, "MercadoPago PHP SDK v" . MP::version);
        curl_setopt($connect, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($connect, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($connect, CURLOPT_CUSTOMREQUEST, $method);
        curl_setopt($connect, CURLOPT_HTTPHEADER, array("Accept: application/json", "Content-Type: " . $content_type));

        return $connect;
    }

SAVE IT AN TEST IT! 

If you have any other problem please....

SCREAM WHILE YOU RUN IN CIRCLES!!!!!

**Comment by Misterio182** [comment]
ATTENTION: The solution presented above should only be used in local environments for testing, and if you use this setting in production environment means a very large security vulnerability.

**Comment by falehenrique** [comment]
Pe
