### ISSUE TITLE
Clone module  for different different choices (monthly payments)

### ISSUE THREAD

**Issue by tdra** [mercadopago/cart-opencart#39]
Is more like a question, how can i clone the module so i can use one for 3 months, 6 months and so on? i use charge per payment method and i wanted to clone the module so i can offer 18months

**Comment by BrunoCodeman** [comment]
@tdra what you mean? You want to offer 18 installments to your customers?

**Comment by tdra** [comment]
i have an extension that adds % for each type of payment so i wanted to have in payment options something like this:

Mercadopago 3 months 
Mercadopago 6 Months
mercadopago 12 months

so i can add them % charge to each one of them

**Comment by BrunoCodeman** [comment]
@tdra You'll have to modify the code and personalize the module to do that.
