### ISSUE TITLE
Integration in Onepage checkout

### ISSUE THREAD

**Issue by tdra** [mercadopago/cart-opencart#40]
the code is this for confirm payment, trying to use transparent payment:

[checkout.txt](https://github.com/mercadopago/cart-opencart/files/118868/checkout.txt)

**Comment by BrunoCodeman** [comment]
@tdra the transparent checkout is not available yet, it was sent to git by a mistake.

**Comment by falehenrique** [comment]
Please, get we last plugin version.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Thank you.
