### ISSUE TITLE
Error country select opencart 2.1.0.2

### ISSUE THREAD

**Issue by monta990** [mercadopago/cart-opencart#41]
Its impossible select other country, this happen

![Error country](https://cloud.githubusercontent.com/assets/2209179/13140055/15d66950-d5ed-11e5-9838-169db1604eb9.png)

**Comment by BrunoCodeman** [comment]
@monta990 are you running it locally or in a server? This call to populate this data is made through SSL, so if the network blocks https calls, this loading will not work,

**Comment by monta990** [comment]
hi, its on server (1and1 hosting)

**Comment by monta990** [comment]
on error log: 2016-02-18 10:04:37 - PHP Notice:  Undefined index: methods in /homepages/4/d609738289/htdocs/admin/controller/payment/mercadopago2.php on line 146

**Comment by martinsimondi** [comment]
si a mi igual!!! en el servidor la corro y nada

**Comment by martinsimondi** [comment]
y categorias igual

**Comment by migrania** [comment]
Buen día, pudieron solucionar este problema??...

**Comment by falehenrique** [comment]
Hola, por favor actualize lo módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias.
