### ISSUE TITLE
Currency Problem

### ISSUE THREAD

**Issue by samxd17** [mercadopago/cart-opencart#43]
Buen día, estoy probandolo en Opencart Versión 2.0.3.1 y tengo ciertos problemas.
Mi moneda principal es el USD$, y la secundaria es el Bolivar Fuerte de Venezuela (VEF).
Hago las pruebas para comprar en BsF y mercadopago no carga el valor en BsF sino el valor en USD$ con el símbolo de BsF.

El codigo al parecer no esta tomando el valor de la moneda seleccionada, que puede estar fallando?

Gracias de antemano.

--------
Good day, I'm testing it in Opencart version 2.0.3.1 and I have some problems.
My main currency is the USD $, and the secondary is the Bolivar Fuerte de Venezuela (VEF).
I do tests to buy in BsF and MercadoPago does not charge BsF value but the value in USD $ with the symbol of BsF.

The code apparently not taking the value of the selected currency, which may be failing?

Thanks in advance.

**Comment by BrunoCodeman** [comment]
@samxd17 

No es posible hacer pagos en USD en Mercado Pago. Acerca  del cambio de valores y monedas, puedes verificar se tienes la configuración correcta para la moneda?

**Comment by samxd17** [comment]
Hola, sí, yo tengo claro que no es posible, yo lo he usado en mi tienda anteriormente como esta configurado: Moneda principial USD y moneda secundaria BsF y tomaba el valor de BsF.
Actualmente esta tomando el valor de USD, asi esté seleccionado BsF.

**Comment by samxd17** [comment]
Cual es la variable que toma la moneda? Ya que esta tomando el valor del dolar y en el checkout esta en BsF! No deberia tomar el valor del dolar en ningun momento. Esta configurado para Venezuela. En BsF

**Comment by samxd17** [comment]
Aqui muestro con fotos mi problema.
Esta es mi configuración de moneda, el codigo ISO esta bien, como de costumbre:
<img src="http://thesamstore.com/image/divisa%20conf.jpg" alt="error mercadopago2" style="max-width:100%;">

En la pagina y el checkout la moneda esta bien como se muestra (en Bs):
(hay un error del envio pero es irrelevante creo ya que uso envio gratuito)
<img src="http://thesamstore.com/image/error%20mercadopago1.jpg" alt="error mercadopago2" style="max-width:100%;">

Al redireccionar a mercadopago.
No toma el valor del checkout en Bs. Sino que toma "9,00"
Que es el valor en USD:
<img src="http://thesamstore.com/image/error%20mercadopago2.jpg" alt="error mercadopago2" style="max-width:100%;">

Necesito ayuda. :cry:

**Comment by samxd17** [comment]
@BrunoCodeman Are you there? you're the best here, save me from this error.
