### ISSUE TITLE
Error en Checkout (2.x)

### ISSUE THREAD

**Issue by IgTS** [mercadopago/cart-opencart#44]
Al llegar al último paso del Checkout, me aparece el siguiente error:

`Notice: Undefined index: shipping_method in /home/nerdcxen/public_html/catalog/controller/payment/mercadopago2.php on line 115Notice: Error: Could not load template /home/nerdcxen/public_html/catalog/view/theme/default/template/default/template/payment/mercadopago2.tpl! in /home/nerdcxen/public_html/system/library/template/basic.php on line 28`

¿Alguna solución?

**Comment by dgarfinkiel** [comment]
Hola, 

En catalog/controller/payment/mercadopago2.php, en la linea 242 elimine "default/template/" 

return $this->load->view('**default/template/**payment/mercadopago2.tpl', $data);

y deberia quedarte asi:

return $this->load->view('payment/mercadopago2.tpl', $data);

Por lo menos asi me esta funcionando bien. 

Saludos y espero sea util.

**Comment by BrunoCodeman** [comment]
Gracias, @dgarfinkiel!

**Comment by dgarfinkiel** [comment]
Por nada @BrunoCodeman. Aprovecho para preguntarte si hay manera de evitar el ingreso de direcciones en MercadoPago OC 2.X ya que no utilizaremos MercadoEnvios y utilizar el pago como invitado, tal como lo funcionaba en la version OC 1.5.X. 

Saludos!

**Comment by BrunoCodeman** [comment]
@dgarfinkiel nuestro equipo de API esta trabajando para corregir este error de las direcciones. Es un error en checkout y no en el modulo.

**Comment by grela** [comment]
Gracias, @dgarfinkiel!
