### ISSUE TITLE
Error en calculo de moneda

### ISSUE THREAD

**Issue by Grupoholeinone** [mercadopago/cart-opencart#45]
Buenos dias, el modulo presenta el siguiente error, nuestra moneda es el Bsf. sin embargo nuestros precios se rigen por $ Dollar americano, cuando totaliza, me mantiene el precio en $ dollar, no multiplica por factor moneda.

**Comment by BrunoCodeman** [comment]
Buenos dias. Cual la versión de OpenCart utilizada?

**Comment by Grupoholeinone** [comment]
Buenos dias, la version utilizada es 2.0.3.1

**Comment by Grupoholeinone** [comment]
Buenos dias, @BrunoCodeman la version utilizada es 2.0.3.1

**Comment by Grupoholeinone** [comment]
esta es nuestra pagina web , podrias hacer una prueba ?  http://www.holeinonevenezuela.com.ve/

**Comment by Grupoholeinone** [comment]
@BrunoCodeman , esta es nuestra pagina web , podrias hacer una prueba ? http://www.holeinonevenezuela.com.ve/

**Comment by BrunoCodeman** [comment]
@Grupoholeinone estoy intentando hacer las pruebas pero cuando yo pulso el botón "comprar", nada ocurre.

**Comment by falehenrique** [comment]
Hola, por favor actualize lo módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias.
