### ISSUE TITLE
Erro no checkout

### ISSUE THREAD

**Issue by eugeniomichetti** [mercadopago/cart-opencart#46]
Olá, 
Estou com um problema na hora do checkout, quando seleciono o meio de pagamento MercadoPago e clico em continuar recebo uma mensagem de erro "Internal Error"
Segue a imagem do erro.
http://i.imgur.com/JGppaGp.png

**Comment by BrunoCodeman** [comment]
Olá, @eugeniomichetti.

Poderias me enviar o log do PHP ou do OpenCart? Acredito que deva ser algum problema de SSL.

**Comment by falehenrique** [comment]
Olá, por favor atualize seu módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Obrigado.
