### ISSUE TITLE
Error Mercado envíos -  MercadoPago OC 2.X

### ISSUE THREAD

**Issue by carlos1602** [mercadopago/cart-opencart#47]
Buen Día Bruno, tengo el siguiente problema:

Al momento de pagar e ingresar los datos de dirección y dar clic en guardar, genera error (Asi sea usuario o invitado):
![image](https://cloud.githubusercontent.com/assets/18661855/14787094/8f479cdc-0ac7-11e6-8915-b36be0d50e52.png)

Hay manera de evitar el ingreso de direcciones en MercadoPago OC 2.X ya que no utilizaré MercadoEnvios y utilizar el pago como invitado, tal como funciona en la version OC 1.5.X.

Agradeszo tu pronta respuesta.

**Comment by josensanchez** [comment]
Alguien pudo resolver este tema? como hay que hacer para quitar la parte de mercadoenvios del pago?

**Comment by falehenrique** [comment]
Hola, por favor actualize lo módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias.
