### ISSUE TITLE
OP 2.X - IPN / Callback not working

### ISSUE THREAD

**Issue by sidneyrees** [mercadopago/cart-opencart#52]
There seems to be an issue on callback method.

A few days ago one of my clients asked me to check why she was not getting emails when a new order was placed.

Reviewed the code and found than on mercadopago2.php (line 220), inside callback function, the method "retorno" is comment out.

Since the module automatically sets the Notification URL to 'index.php?route=payment/mercadopago2/callback', shouldn't it callback method call retorno() ?

Currently, callback is just a redirects to checkout success page.

File: [cart-opencart/v2.x/standard/catalog/controller/payment/mercadopago2.php](https://github.com/mercadopago/cart-opencart/blob/master/v2.x/standard/catalog/controller/payment/mercadopago2.php)

```
public function callback() {

		//$this->retorno();

		$this->response->redirect($this->url->link('checkout/success'));

}
```

I had un-commented that line and fix the issue. Now emails are sent and the order status is correctly set (orders previous to this fix has empty status)

There is another small issue on the same file $dados['collection']['payment_method_id'] is undefined.

I debug a Mercado Pago response and found that the most similar field is $dados['collection']['payment_type'] ... so I replace all apparitions of $dados['collection']['payment_method_id'] with $dados['collection']['payment_type']

**Comment by falehenrique** [comment]
Hi, please update your plugin.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Thank you.
