### ISSUE TITLE
Error en el checkout

### ISSUE THREAD

**Issue by alejo684** [mercadopago/cart-opencart#53]
Que tal, recibo este error:  Notice: Error: Could not load template /srv/disk5/661058/www/visitemendoza.com/catalog/view/theme/default/template/default/template/payment/mp_standard.tpl! in /srv/disk5/661058/www/visitemendoza.com/system/library/template/basic.php on line 26

alguna idea? gracias

**Comment by fnotti** [comment]
Ese archivo es el template que viene en el paquete de distribución... lo unico que veo medio extraño es que en la URL está duplicada esta parte "theme/**default/template/default/template**/". según recuerdo la ruta no es esa... aqui la ruta está armada así:

(la real) /catalog/view/theme/default/template/payment/mp_standard.tpl
(la tuya) /catalog/view/theme/default/template/default/template/payment/mp_standard.tpl

De mendocino a mendocino! ;) Saludos y mandame unas tortitas raspadas!

**Comment by alejo684** [comment]
Era exactamente eso! lo descubrí el otro día analizando el directorio del error y me di cuenta que lo buscaba mal el opencart.

Gracias!! y Saludos!!

**Comment by josensanchez** [comment]
@alejo684 y como lo solucionaste? estoy con el mismo problema... supongo que cambiaste alguna ruta de las configs.
estaria muy agradecido si me pasas cual ruta cambiaste.

**Comment by alejo684** [comment]
catalog/view/theme/default/template/**default/template/payment**/mp_standard.tpl!" eso es lo que ves en el error

 /catalog/view/theme/default/template/payment/mp_standard.tpl esta es la real de la carpeta, entras a tu ftp y creas carpetas para que te quede asi 

catalog/view/theme/default/template**/default/template**/payment/mp_standard.tpl

saludos

**Comment by fedesanchez** [comment]
Hola @alejo684 , la solución que planteás es válida pero me gustaria encontrar donde se origina el problema. Tengo la teoría de que se debe a la version de php... estas usando php 7 ? y estas usando algun theme o template que no viene por default en opencart?

**Comment by fnotti** [comment]
El .tpl queda identificado en el código del mp_standard.php (busquen el texto tpl con el editor y lo verán)... la ruta relativa en la situación de instalación podría requerir de un ajuste de la cadena que se arma para identificar la ruta... no parece gran cosa.

Saludos.-
