### ISSUE TITLE
Error en el Setup de Pagos

### ISSUE THREAD

**Issue by Grupoholeinone** [mercadopago/cart-opencart#58]
una vez incorporados los datos en el setup, no te permite grabar las modificaciones

**Comment by fnotti** [comment]
Me pasó  lo mismo pero crei que era problema de MijoChar... debí cambiar el botón de Save por el mismo botón que hay en el Gateway de PayPal Standard... tal como está ahi pegarlo en lugar del <A> que tienen en su lugar en tú código ajustando solo el nombre del FORM al que apunta... ahora graba bien. No tengo el código "cerca" si no te lo pegaba pero por ahi te das maña.

Espero te sirva.

**Comment by falehenrique** [comment]
Hola, por favor actualize lo módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias.
