### ISSUE TITLE
error en checkout

### ISSUE THREAD

**Issue by hudson940** [mercadopago/cart-opencart#59]
Fatal error: Uncaught exception 'MercadoPagoException' with message 'internal_error' in /home/macizosc/public_html/catalog/controller/payment/mercadopago.php:463 Stack trace: #0 /home/macizosc/public_html/catalog/controller/payment/mercadopago.php(484): MPRestClient::exec(Array) #1 /home/macizosc/public_html/catalog/controller/payment/mercadopago.php(58): MPRestClient::post(Array) #2 /home/macizosc/public_html/catalog/controller/payment/mercadopago.php(195): MP->get_access_token() #3 /home/macizosc/public_html/catalog/controller/payment/mp_standard.php(180): MP->create_preference(Array) #4 [internal function]: ControllerPaymentMPStandard->index(Array) #5 /home/macizosc/public_html/system/engine/action.php(44): call_user_func_array(Array, Array) #6 /home/macizosc/public_html/system/engine/loader.php(21): Action->execute(Object(Registry), Array) #7 /home/macizosc/public_html/catalog/controller/checkout/confirm.php(419): Loader->controller('payment/mp_stan...') #8 [internal function]: ControllerCheckoutConfirm->index() #9 /h in /home/macizosc/public_html/catalog/controller/payment/mercadopago.php on line 463
![image](https://cloud.githubusercontent.com/assets/19626013/15628730/3402f102-24ce-11e6-96d6-18b8ee850f66.png)

**Comment by falehenrique** [comment]
Olá, por favor atualize seu módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Obrigado.
