### ISSUE TITLE
Cupom de desconto não funciona.

### ISSUE THREAD

**Issue by tulioreis27** [mercadopago/cart-opencart#61]
Estou usando a versão 2.0.3.1 do OpenCart e a versão Standard do Mercado pago. Cadastro um cupom na minha loja, e permanece tudo certo até a tela de resumo do pedido. Após clicar em PAGAR o desconto do cupom desaparece quando o lingtbox do MP surge. Fica o preço original sem desconto. Se eu marco a opção frete grátis, esse também é cobrado após clicar em PAGAR.

Alguém já teve esse problema e resolveu?

Desde já agradeço

**Comment by BrunoCodeman** [comment]
Oi, Túlio!

Esse cupom de desconto que tu estás usando é aplicado sobre o produto diretamente ou sobre o valor total da venda? Pois no checkout standard é enviada a lista de produtos e a API calcula o valor final em cima dos preços. Então, se o cupom aplica diretamente sobre o valor final, no checkout standard ele não irá aplicar esse desconto, apenas se for um cupom de desconto por produto. No caso do checkout transparente, ocorre o contrário: O desconto é aplicado diretamente sobre o valor final.

Estamos analisando como vamos contornar essa situação, visto que não é um bug mas sim uma situação onde o fluxo da plataforma OpenCart é diferente do fluxo do MercadoPago. Acredito que no próximo release já tenhamos isso implementado.

**Comment by falehenrique** [comment]
Hola, por favor actualize lo módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias.

**Comment by falehenrique** [comment]
@tulioreis27  por favor atualize seu módulo para a última versão.

Obrigado.

**Comment by tulioreis27** [comment]
Olá amigo, ainda não está funcionado. Me aparece o seguinte erro:

Warning: Missing argument 2 for ModelTotalCoupon::getTotal(), called in /home/cabec217/public_html/rebootstore.com.br/catalog/controller/payment/mp_standard.php on line 75 and defined in /home/cabec217/public_html/rebootstore.com.br/catalog/model/total/coupon.php on line 3Warning: Missing argument 3 for ModelTotalCoupon::getTotal(), called in /home/cabec217/public_html/rebootstore.com.br/catalog/controller/payment/mp_standard.php on line 75 and defined in /home/cabec217/public_html/rebootstore.com.br/catalog/model/total/coupon.php on line 3Notice: Undefined variable: total in /home/cabec217/public_html/rebootstore.com.br/catalog/model/total/coupon.php on line 79Notice: Undefined variable: total in /home/cabec217/public_html/rebootstore.com.br/catalog/model/total/coupon.php on line 80Notice: Undefined variable: total in /home/cabec217/public_html/rebootstore.com.br/catalog/model/total/coupon.php on line 90

E quando clico em Pagar, mesmo com o erro, continua não puxando o desconto do cupom.

att,

Túlio Reis

**Comment by adefoz** [comment]
Estou com o mesmo problema. Minha extensão do Mercado Pago não reconhece o desconto. Aonde encontro a solução? A versão do meu OC é a 2.2.0.0
