### ISSUE TITLE
Error al aplicar descuento

### ISSUE THREAD

**Issue by chechirussel2** [mercadopago/cart-opencart#65]
Estoy utilizando la ultima versión de Open Cart y tengo el siguiente problema con el modulo de MercadoPago: 

Al aplicar algún tipo de descuento al carrito (probé con varios módulos) no se hace efectivo al momento del pago. Es decir, en el carrito figura el descuento sobre el monto "total" pero al momento de realizar el pago con MercadoPago no lo toma.

**Comment by BrunoCodeman** [comment]
Hola!

El descuento que hablas es directamente en el carrito o es un descuento por producto?

**Comment by chechirussel2** [comment]
Hola, el descuento es aplicado sobre el monto total, es decir, a un determinado precio final se le aplica un porcentaje de descuento. Cabe aclarar que el envió tampoco lo suma (es una tarifa plana)

Aca se detallan los precios del envío, descuento y total:
![1](https://cloud.githubusercontent.com/assets/19142020/16927628/ae5f4f5a-4d04-11e6-9bde-18498a9fcd68.png)

Y esto es al momento de pagar. Como se ve, no se sumo el gasto de envío ni tampoco se aplicaron los descuentos:
![2](https://cloud.githubusercontent.com/assets/19142020/16927674/eb1fed28-4d04-11e6-9ab2-3297a7ac75a5.png)

Te dejo la plagina web donde estoy aplicando el modulo de MP por las dudas: http://8qinspira.com/
Gracias Bruno por tu tiempo.

**Comment by chechirussel2** [comment]
@BrunoCodeman Buen día Bruno, necesito una respuesta ya que tengo el E-commerce funcionando con este error.

Desde ya muchas gracias.

Saludos!

**Comment by BrunoCodeman** [comment]
Hola, @chechirussel2. Yo le pido que contacte directamente MercadoPago, porque yo no trabajo más para la empresa. Gracias.

**Comment by tdra** [comment]
yo tengo el mismo problema, ya tiene solucion? :/

**Comment by nkeYy** [comment]
Yo tengo el mismo problema, he visto el código fuente y lo comparé con el de Khipu que sí envía correctamente el valor, existe una variable $totalprice, la reemplacé por lo de Khipu y nada, lo reemplacé por un valor fijo y nada... Seguí viendo el código y me di cuenta que jamás se envía ese valor a mercado libre, sólo se envían los items y el sistema de mercadopago suma los items y muestra el valor. 
La solución es crear un item fantasma de igual valor del descuento. Trabajo en ello. ;)

**Comment by falehenrique** [comment]
Hola por favor actualize su módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias

**Comment by chechirussel2** [comment]
No funciona. sigue sin restar los descuentos.

**Comment by tdra** [comment]
yo tambien tengo el mismo problema, y ahora con el modulo actualizado al usar un cupon sale igual un error dentro de la plantilla @falehenrique

**Comment by tdra** [comment]
porque este tema esta como cerrado si todavia sigue el problema

**Comment by hazmodan** [comment]
Listo, lo solucione. Opencart 2.1.0.1 plugin mercadopago https://www.mercadopago.com.ve/developers/es/tools/modules/opencart/

**Comment by samxd17** [comment]
tengo el mismo problema. Con Opencart 2.0.3.1
Pero con la comisiones adicionales.
Me toma el valor del subtotal y no del total con la suma de las comisiones.
Al redirigir al mercadopago toma el valor del subtotal. :(
Alguna solución? porque los archivos actualizados me siguen dando el mismo problema..

**Comment by tdra** [comment]
que asco que aun no hayan arreglado este problema

**Comment by tdra** [comment]
sigue tomando el plugin el subtotal y no el total, saltandose cualquier % de descuento o de incremento
