### ISSUE TITLE
error in checkout

### ISSUE THREAD

**Issue by JoseMariani** [mercadopago/cart-opencart#66]
Cuando proceso la compra despues de llenar los datos me sale un error con codigo s4033

**Comment by gmatsuoka** [comment]
Hola @JoseMariani, todo bien?

No muestra ningún mensaje sólo el número de error?

Slds

**Comment by falehenrique** [comment]
Hola por favor actualize su módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias
