### ISSUE TITLE
Error en Mercadopago 2.0 Standard Checkout usando "Redirect"

### ISSUE THREAD

**Issue by pablocipriani** [mercadopago/cart-opencart#67]
Saludos, Uso Opencart 2.0 y Mercadopago 2.0 del 6 de Julio con la opcion REDIRECT. 
Al hacer el redirect a Mercadopago para la compra todo perfecto, si decido regresar al carrito de compras usando el link provisto en la parte inferior o luego de procesar el pago correctamente obtengo este error:

"Notice: Undefined index: status in /home/multipar/public_html/catalog/controller/payment/mp_standard.php on line 236Warning: Cannot modify header information - headers already sent by (output started at /home/multipar/public_html/index.php:102) in /home/multipar/public_html/system/library/response.php on line 12"  Alguna sugerencia?.

**Comment by falehenrique** [comment]
Hola por favor actualize su módulo.

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=26703&filter_search=mercadopago

Gracias
