### ISSUE TITLE
 Permission Denied! al tratar de Guardar Configuracion del Modulo

### ISSUE THREAD

**Issue by tigrexmcbo** [mercadopago/cart-opencart#68]
Hola, 
Estoy usando la Version 2.3.0.2 de Open Cart
Cuando trato de guardar la configuración del modulo de Mercadopago me arroja el siguiente error:

 Permission Denied!
You do not have permission to access this page, please refer to your system administrator.

Instale el Modulo de MP 2.x
Standar
Custom
Ticket

Fui hasta la seccion Settings ->Users -> UserGroups para ver la permisologia del grupo "Administrator" y me di cuenta que ni siquiera aparece el modulo de Mercadopago que he instalado, entre los permisos.

¿Alguien ha tenido el mismo error? Como podría corregir esto? se pueden añadir los permisos correspondientes manualmente editando la BD?

De antemano muchas gracias al que me desee ayudar.

**Comment by falehenrique** [comment]
Hola tudo bien, usted necesita añadir las permisos para lo modulo instalado.

Gracias.

**Comment by carscx** [comment]
Alguna novedad? Esto pasa en la ultima version de OpenCart!
