### ISSUE TITLE
Tengo un problema al confirmar la compra

### ISSUE THREAD

**Issue by outthesystem** [mercadopago/cart-opencart#70]
El drama es que cuando llego al Paso 6: Confirmar Compra no me sale el boton de Confirmar compra para poder redirigirme a mercadopago, cual es el prblema?

tengo php 7 y mysql 5.6

**Comment by alexandrol** [comment]
Hola Juancecba82, ¿puedes explicar mejor la solución que planteas?

**Comment by Juancecba82** [comment]
Que parte no es la que comprendes?
Yo lo que verifiqué es que la ruta de todos los directorios del plugin no concuerdan con la estructura de directorio de OpenCart.

A modo de ejemplo:

El plugin me indica que debo colocar la carpeta "plugin" dentro de "carpeta1" que se encuentra dentro de la carpeta "Admin". Pero revisando la estructura de directorios del CMS no existe tal "carpeta1" sino que existe una llamada "extensions", y luego, ahí dentro SI EXISTE esa "carpeta1" que es a donde iría mi carpeta "plugin" del gateway de mercadopago.

Y así pasa con casi todos los directorios.

No se si el autor modificase esas líneas, el plugin funcionaría correctamente, pero es solo un detalle que logré ver al analizar el código fuente de algunos archivos del plugin.

**Comment by flaviofat** [comment]
¿Hola todo bien? Estamos trabajando en una nueva versión para OpenCart 2.3. Tan pronto como sea posible vamos a disponibilizar una nueva versión del modulo!

**Comment by flaviofat** [comment]
Olá a todos! Esta disponível a nova versão do mercado pago para o OpenCart 2.3. Por favor acesse o link abaixo para obter esta nova versão:

Hello everyone! The new version of the paid market for OpenCart 2.3 is available. Please go to the link below to get this new version:

¡Hola a todos! Esta disponible la nueva versión de mercado pago por OpenCart 2.3. Por favor visite el siguiente enlace para esta nueva versión:

https://github.com/mercadopago/cart-opencart

**Comment by naza1** [comment]
Hola tengo instalado la Versión de Opencart 2.0.3 y me sigue pasando esto, como puede ser?
