### ISSUE TITLE
Problema de permisos

### ISSUE THREAD

**Issue by cocon78** [mercadopago/cart-opencart#71]
Hola, tengo el mismo problema que la consulta anterior:
Estoy usando la Version 2.3.0.2 de Open Cart
Cuando trato de guardar la configuración del modulo de Mercadopago me arroja el siguiente error:

Permission Denied!
You do not have permission to access this page, please refer to your system administrator.

Fui hasta la seccion Settings ->Users -> UserGroups para ver los permisos del grupo "Administrator" y  SI esta tildada/marcada la opción del permiso.

 Como podría corregir esto?

Muchas Gracias!

**Comment by platiniumhost** [comment]
Hola, pudiste resolver el inconveniente ? hemos buscado la solución a esto y no la conseguimos por el momento, alguna ayuda o guía ? gracias

**Comment by cocon78** [comment]
Hola. 
No lo pude solucionar.
Lamentablemente tuve que desistír se usar esta opción.

**Comment by platiniumhost** [comment]
Hola, Si esto esta complicado, no hay sugerencia por ninguna parte :S

**Comment by alexandrol** [comment]
Hola, ¿alguna actualización sobre ese tema? ¿alguien ha logrado solucionar y usar el modulo?

Saludos

**Comment by platiniumhost** [comment]
Saludos, yo lo resolví simplemente instalando la versión anterior manualmente del opencart y listo funciono.

Porque realice hasta la instalación por archivos de la versión anterior con la nueva y nada.

Así que esta fue mi solución por el momento y funciona el responsive que era muy importante para mi.

**Comment by cocon78** [comment]
Excelente!! Específicamente que versión? Porque yo también  probé otras versiones y tampoco lo pude hacer andar

**Comment by platiniumhost** [comment]
Saludos, mil disculpa por mi tardanza,

La versión que utilice fue: 2.1.0.2

Y funciono perfecto sin problemas.

Saludos.

**Comment by alexandrol** [comment]
Pregunta para Mercadopago ¿Tienen planeado publicar alguna actualización para la versión 2.3?

Saludos

**Comment by alexandrol** [comment]
Probe con la 2.2.0.0 y funciona bien, sin embrago, no considero esto una solución pues lo deseable es trabajar con la última version estable.

**Comment by carscx** [comment]
Alguna novedad con respecto a esto? Alguien sabe, como modificar el modulo, para que no pida esa verificacion, o hardcodearla de alguna manera?

**Comment by danpeig** [comment]
Workaround for the permission bug.

1. Open your MySQL Admin tool, point to your OpenCart DB and go to the "user_group" table.

2. Inside the desired user group records (Administrador, for example), replace the following text in the "permission" field. There are two entries, one for access and the other for modification:

Original text: `"payment\/mp_standard"`
Replaced text: `"payment\/mp_standard","extension\/payment\/mp_standard"`

3. The module should work now. You may still get the error after saving the modifications but they will save correctly.

**Comment by alexandrol** [comment]
This permission was already in my database, however, the problem persists

**In the administrator:**
Drop a "Permission Denied!" Screen At the end of recording the configuration.

**In the shop**
When you get to step 6 (Order Confirmation), the sistem place the detail of the order, but do not display the information to process the payment.

Regards

**Comment by juangrafico** [comment]
Gente! Tengo la versión 2.3 y con esta solución que publicó Danpeig me funcionó. Hago Copy / Paste:

Workaround for the permission bug.

Open your MySQL Admin tool, point to your OpenCart DB and go to the "user_group" table.

Inside the desired user group records (Administrador, for example), replace the following text in the "permission" field. There are two entries, one for access and the other for modification:

Original text: "payment\/mp_standard"
Replaced text: "payment\/mp_standard","extension\/payment\/mp_standard"

The module should work now. You may still get the error after saving the modifications but they will save correctly.

**Comment by flaviofat** [comment]
¿Hola todo bien? Estamos trabajando en una nueva versión para OpenCart 2.3. Tan pronto como sea posible vamos a disponibilizar una nueva versión del modulo!

**Comment by waguero** [comment]
Cuanto tiempo mas calculan que llevará solucionar el problema que plantean como así también que aparezca el botón al confirmar la orden de compra y de esta manera llamar a la api de mercado de pago?

**Comment by flaviofat** [comment]
Olá a todos! Esta disponível a nova versão do mercado pago para o OpenCart 2.3. Por favor acesse o link abaixo para obter esta nova versão:

Hello everyone! The new version of the paid market for OpenCart 2.3 is available. Please go to the link below to get this new version:

¡Hola a todos! Esta disponible la nueva versión de mercado pago por OpenCart 2.3. Por favor visite el siguiente enlace para esta nueva versión:

https://github.com/mercadopago/cart-opencart
