### ISSUE TITLE
Problema con total y sub-total

### ISSUE THREAD

**Issue by samxd17** [mercadopago/cart-opencart#72]
Buen dia estimado equipo y demás desarrollodares.

Tengo un problema con este plugin y otro. En Venezuela.
Tengo Opencart 2.0.3.1

Y estoy usando la extensión paga "Payment Type Fee (1.5.x-2.1.x)" para añadir un 8% de comisión a cada metodo de pago.
A Mercadopago le coloco su respectivo 8%
Y por ejemplo:
En el carrito funciona bien... y sale asi:
Subtotal: 100 BsF
Comisión de procesamiento: 8 BsF
Total: 108 BsF

Al redirigir a mercadopago para el pago. Sale monto a pagar: 100 BsF
Esta tomando el subtotal. No el Total!! deberia cargar en mercadopago el valor del total a pagar es decir 108 bsF.!

Y este problema es con el modulo de mercadopago, ya que con el de Paypal y bitcoin si toma el valor del total cuando redirige a dichas plataformas para el pago.

Alguna idea? porque mercadopago esta tomando el valor del Subtotal y no del total.?

Gracias de antemano.

**Comment by josensanchez** [comment]
Yo estoy teniendo un problema similar pero con descuentos: tengo 2x1 en algunos productos y va todo bien hasta que se abre el iframe de MP: Me muestra el subtotal y no el total.

según estoy viendo en la API del standard checkout 

https://www.mercadopago.com.ar/developers/en/api-docs/basic-checkout/checkout-preferences/

no hay forma de pasarle el precio total de la compra, MP lo calcula sumando los valores de unit_price de los items y punto

Eso no sería lo correcto. 

Tal vez haya que usar si o si el Custom Checkout. 

es así?

**Comment by josensanchez** [comment]
Yo estoy teniendo un problema similar pero con descuentos: tengo 2x1 en algunos productos y va todo bien hasta que se abre el iframe de MP: Me muestra el subtotal y no el total.

según estoy viendo en la API del standard checkout 

https://www.mercadopago.com.ar/developers/en/api-docs/basic-checkout/checkout-preferences/

no hay forma de pasarle el precio total de la compra, MP lo calcula sumando los valores de unit_price de los items y punto

Eso no sería lo correcto. 

Tal vez haya que usar si o si el Custom Checkout. 

es así?

**Comment by tdra** [comment]
es encerio que aun no se resuelve el problema?

**Comment by samxd17** [comment]
Para el Custom Checkout yo necesitaría ir a "producción" en mercadopago, para ello exigen tener activo el certificado SSL. por lo que yo necesitaría renovar mi certificado SSL eso me costaría 70$ al año.

Ahora, hay alguien que tenga el SSL activo y le funcione bien el Custom Checkout?
Ya que no quiero gastar 70$ para que igual no me funcione el Custom Checkout, ya que como estoy, no necesito SSL, ya que ningun cliente necesita colocar datos delicados en la web, sino hacer los pagos directo desde su banco.

**Comment by tdra** [comment]
yo tenia SSL en un dominion y tenia aun el problema

**Comment by samxd17** [comment]
@tdra pero con el standard checkout o el custom checkout? ya que el problema al parecer es con el standard checkout.

Ahora, para usar el custom checkout es que se necesita tener el  SSL activo.

**Comment by tdra** [comment]
probe ambos, en ninguno servia

**Comment by flaviofat** [comment]
Hola, una nueva versión estará disponible esta semana, por favor ver si su problema ha sido resuelto!
