### ISSUE TITLE
Pedidos acima de 1000 - erro no parcelamento

### ISSUE THREAD

**Issue by rdmegna** [mercadopago/cart-opencart#73]
Nos pedidos acima de R$1.000,00 há um erro causado pela linha 214.
O js faz a troca de ',' por '.' e o resultado é R$1.000.00

Então valor para parcelamento fica de apenas R$1.00 em 1x.

**Comment by flaviofat** [comment]
Olá tudo bem? Uma nova versão será disponibilizada nesta semana, por favor, veja se seu problema foi corrigido! Obrigado!
