### ISSUE TITLE
MercadoPago Standard Checkout Not Working with OpenCart 2.1.0.2 / MercadoPago Standard Checkout no funciona con OpenCart 2.1.0.2

### ISSUE THREAD

**Issue by scriptsanddesigns** [mercadopago/cart-opencart#74]
Hi,

I'm using OpenCart 2.1.0.2 with Latest Version of MercadoPago Standard Checkout Module 

When trying to Checkout in Confirm Order Step below error is thrown

Kindly requesting MercadoPago experts/team Help me to fix this Issue

Mode: Sandbox/Test
Currency: Argentum (ARG)
MercadoPago Checkout type: Standard using Redirect
Opencart version - 2.1.0.2

Kindly help us on below error

Fatal error: Uncaught exception 'MercadoPagoException' with message 'unit_price must be a number' in /home/sanddonline/public_html/catalog/controller/payment/mercadopago.php:476 Stack trace: #0 /home/sanddonline/public_html/catalog/controller/payment/mercadopago.php(497): MPRestClient::exec(Array) #1 /home/sanddonline/public_html/catalog/controller/payment/mercadopago.php(212): MPRestClient::post(Array) #2 /home/sanddonline/public_html/catalog/controller/payment/mp_standard.php(231): MP->create_preference(Array) #3 [internal function]: ControllerPaymentMPStandard->index(Array) #4 /home/sanddonline/public_html/system/storage/modification/system/engine/loader.php(42): call_user_func(Array, Array) #5 /home/sanddonline/public_html/catalog/controller/checkout/confirm.php(409): Loader->controller('payment/mp_stan...') #6 [internal function]: ControllerCheckoutConfirm->index(Array) #7 /home/sanddonline/public_html/system/storage/modification/system/engine/action.php(46): call_user_func(Array, Array) #8 /home/sanddonline/public_html/syst in /home/sanddonline/public_html/catalog/controller/payment/mercadopago.php on line 476

Thanks

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Hola,

Estoy usando OpenCart 2.1.0.2 con la última versión de MercadoPago Standard Checkout Module

Cuando se intenta realizar la comprobación en el paso de confirmación de la orden siguiente se arroja

Por favor, solicite expertos / equipo de MercadoPago Ayúdeme a solucionar este problema

Modo: Sandbox / Prueba
Moneda: Argentum (ARG)
Tipo de comprobación: Estándar utilizando Redirect
Versión de Opencart - 2.1.0.2

Por favor, ayúdenos en el siguiente error

Fatal error: Uncaught exception 'MarketPagoException' con el mensaje 'unit_price debe ser un número' en /home/sanddonline/public_html/catalog/controller/payment/mercadopago.php:476 Rastreo de la pila: # 0 / home / sanddonline / public_html / catalog / MPRestClient :: exec (Array) # 1 /home/sanddonline/public_html/catalog/controller/payment/mercadopago.php(212): MPRestClient :: post (Array) # 2 / / Internal / sanddonline / public_html / public_html / catalog / controller / payment / mp_standard.php (231): MP-> create_preference (Array) # 3 [función interna]: ControllerPaymentMPStandard-> Public_html / system /storage/modification/system/engine/loader.php(42): call_user_func (Array, Array) # 5 /home/sanddonline/public_html/catalog/controller/checkout/confirm.php (409): Loader-> Controlador (7): [6] [6] [6] [7] [7] Array, Array) # 8 / home / sanddonline / public_html / sys en / home / sanddonline / public_html / catalog / controller / payment / Mercadopago.php en la línea 476

Gracias

**Comment by scriptsanddesigns** [comment]
Fatal error: Uncaught exception 'MercadoPagoException' with message 'unit_price must be a number' in /home/sanddindia/public_html/catalog/controller/payment/mercadopago.php:476 Stack trace: #0 /home/sanddindia/public_html/catalog/controller/payment/mercadopago.php(497): MPRestClient::exec(Array) #1 /home/sanddindia/public_html/catalog/controller/payment/mercadopago.php(212): MPRestClient::post(Array) #2 /home/sanddindia/public_html/catalog/controller/payment/mp_standard.php(231): MP->create_preference(Array) #3 [internal function]: ControllerPaymentMPStandard->index(Array) #4 /home/sanddindia/public_html/system/storage/modification/system/engine/loader.php(42): call_user_func(Array, Array) #5 /home/sanddindia/public_html/catalog/controller/checkout/confirm.php(409): Loader->controller('payment/mp_stan...') #6 [internal function]: ControllerCheckoutConfirm->index(Array) #7 /home/sanddindia/public_html/system/storage/modification/system/engine/action.php(46): call_user_func(Array, Array) #8 /home/sanddindia/public_html/syst in /home/sanddindia/public_html/catalog/controller/payment/mercadopago.php on line 476

**Comment by ferezini** [comment]
Não abre nenhuma opção quando escolho mercado pago, na aba de pagamento e fica travado. opencart 2.3.

**Comment by carloskyo** [comment]
Aqui no 2.3 também não aparece nada depois que escolho mercado pago opencart 2.3

**Comment by ferezini** [comment]
tem q colocar algum javascript em alguma pagina? me deem uma luz

**Comment by flaviofat** [comment]
@scriptsanddesigns Hola, una nueva versión estará disponible esta semana, intenta ver si su problema resuelto!

@ferezini @carloskyo : Tudo bem? Iremos disponibilizar uma nova versão para OpenCart 2.3 o quanto antes, pois estamos trabalhando nisso!

**Comment by scriptsanddesigns** [comment]
@flaviofat whether new release will fix the issue in opencart 2.1.0.2

**Comment by tdra** [comment]
@flaviofat any new with the date of the update? have the same problem here

**Comment by samxd17** [comment]
Same problem Here.
![image](https://cloud.githubusercontent.com/assets/16740015/23236701/97012454-f930-11e6-97bd-d3cb7c65167a.png)

**Comment by tdra** [comment]
still no response or update :/

**Comment by flaviofat** [comment]
Olá a todos! Esta disponível a nova versão do mercado pago para o OpenCart 2.3. Por favor acesse o link abaixo para obter esta nova versão:

Hello everyone! The new version of the paid market for OpenCart 2.3 is available. Please go to the link below to get this new version:

¡Hola a todos! Esta disponible la nueva versión de mercado pago por OpenCart 2.3. Por favor visite el siguiente enlace para esta nueva versión:

https://github.com/mercadopago/cart-opencart

**Comment by flaviofat** [comment]
@scriptsanddesigns Hello, how are you? So, you need get the new code of mercado pago, you maked this?

**Comment by tdra** [comment]
@flaviofat does it work with 2.1? we are waiting for month for a fix for opencart 2.x not for 2.3

**Comment by diegolupinacci** [comment]
Hola, 
estoy con la version de OC 2.1.0.2 también, y he bajado la última versión de este plugin pero sigue sin funcionar.

En el error log da lo siguiente:

[Wed Mar 22 12:37:47.108248 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: currentnull, referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108299 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'MercadoPagoException' with message 'error setting certificate verify locations:, referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108305 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr:   CAfile: /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/cacert.pem, referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108309 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr:   CApath: /etc/ssl/certs' in /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/mercadopago.php:503, referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108331 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: Stack trace:, referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108335 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #0 /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/mercadopago.php(544): MPRestClient::exec(Array), referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108339 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #1 /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/mercadopago.php(58): MPRestClient::post(Array), referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108343 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #2 /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/mercadopago.php(236): MP->get_access_token(), referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108347 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #3 /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/mp_standard.php(193): MP->create_preference(Array), referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108351 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #4 [internal function]: ControllerPaymentMPStandard->index(Array), referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108355 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #5 /var/www/vhosts/dominio.uy/httpdocs/vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(42): call_user_func(Array, Array), referer: https://dominio.uy/pagar.html
[Wed Mar 22 12:37:47.108359 2017] [fcgid:warn] [pid 9948] [client 167.60.204.104:54307] mod_fcgid: stderr: #6 /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/d_quickc in /var/www/vhosts/dominio.uy/httpdocs/catalog/controller/payment/mercadopago.php on line 503, referer: https://dominio.uy/pagar.html

Si alguien sabe que es agradezco respuesta.

Saludos!!!

**Comment by diegolupinacci** [comment]
Bueno, he llegado a una solución para los problemas que tiene el módulo 2.x

Inicialmente agradezco la respuesta de Flavio en la que me da estos datos:

*************************************************************************************************************************
estas com problemas em su servidor com requisições HTTP devido a su certificado SSL.

Abaixo tengo alguns passos a serguir que pode ajudar.

Cuando la API devuelve el código de estado 0, es porque no ha sido posible acceder a la API. Puede haber tres razones:
a- Inestabilidad de Internet
b- Ausencia de los paquetes PHP Curl.
Realizar la instalación mediante el comando: sudo apt-get install php5-curl  (ubuntu).
Reinicie el servidor.
c- La ausencia de un certificado digital, para resolver este problema siga los siguientes pasos:
Descargue un certificado desde http://curl.haxx.se/docs/caextract.html
Agregue la siguiente línea en el archivo php.ini (la dirección debe asignar a la ubicación de donde se encuentra el certificado):
[curl]
curl.cainfo=c:\php\certificado\cacert.pem

*************************************************************************************************************************

De esto lo que está bien es es faltaba el certificado cacert.pem
El mismo no es necesario bajarlo de la url mencionada anteriormente, sino que hay que buscarlo en la carpeta del tipo custom:
"cart-opencart-master\v2.x - 2.2\custom\catalog\controller\payment"

Allí está el archivo y deben colocarlo en la misma ubicación que está. Ya que el módulo lo busca ahí.

Luego deben cambiar también en el archivo "cart-opencart-master\v2.x - 2.2\standard\catalog\controller\payment\mp_standard.php"

en la linea 77 este archivo

esto:

$total = $this->currency->format($order_info['total'] - $this->cart->getSubTotal(), $order_info['currency_code'], false, false);

por esto:

$total = round(($order_info['total'] - $this->cart->getSubTotal()) * $order_info['currency_value'], 2);
		if($this->config->get('mp_standard_country') == 'MCO'){
			$total = $this->currency->format($order_info['total'] - $this->cart->getSubTotal(), $order_info['currency_code'], false, false);
		}

Ya que sino enviaba el valor como string y daba error al enviar los datos a la API.

Por último (al menos hasta ahora) se debe cambiar la linea 254 del mismo archivo.

Esto:

$this->response->setOutput($this->load->view('payment/mp_standard_success', $data));


por esto:

$this->response->setOutput($this->load->view('default/template/payment/mp_standard_success.tpl', $data));

Y con eso tenemos el módulo funcionando.

El problema que tengo ahora es que solo funciona con el checkout standar de OpenCart y yo uso un OnePage CheckOut.
Así que seguiré trabajando para ver si lo puedo solucionar y lo publicaré luego.

Saludos!

**Comment by gmatsuoka** [comment]
Hola a todos,

Vamos a cerrar esta issue, ya que la mayoría de los temas relacionados con los errores citados aquí se han resuelto.

Slds,

Gabriel.

**Comment by yaelduckwen** [comment]
@gmatsuoka los errores que se nombran siguen saliendo
