### ISSUE TITLE
Não abre nenhuma opção quando escolho mercado pago, na aba de pagamento e fica travado. opencart 2.3.

### ISSUE THREAD

**Issue by ferezini** [mercadopago/cart-opencart#75]
Não abre nenhuma opção quando escolho mercado pago, na aba de pagamento e fica travado. opencart 2.3.

**Comment by carloskyo** [comment]
Mesma coisa aqui.

**Comment by ferezini** [comment]
tem q colocar algum javascript em alguma pagina? me deem uma luz pfv

**Comment by flaviofat** [comment]
Olá tudo bem? Estamos trabalhando em uma nova versão para o Opencart 2.3. Assim que possível iremos disponibilizar o quanto antes!

**Comment by waguero** [comment]
Olá, hoje é 27 de fevereiro de 2017, quando se espera liquidar o api para OpenCart 2.3.0.2

**Comment by flaviofat** [comment]
Olá a todos! Esta disponível a nova versão do mercado pago para o OpenCart 2.3. Por favor acesse o link abaixo para obter esta nova versão:

Hello everyone! The new version of the paid market for OpenCart 2.3 is available. Please go to the link below to get this new version:

¡Hola a todos! Esta disponible la nueva versión de mercado pago por OpenCart 2.3. Por favor visite el siguiente enlace para esta nueva versión:

https://github.com/mercadopago/cart-opencart

**Comment by waguero** [comment]
Hola @flaviofat , sigue sin funcionar. "INTERNAL SERVER ERROR" cuando se presiona boton "continuar" en Métodos de Pago.
Olá, ainda não funciona. "INTERNAL SERVER ERROR" quando o botão é pressionado "continuar" em Métodos de pagamento.
![imagen](https://cloud.githubusercontent.com/assets/6276225/23635737/30e75b46-02b0-11e7-99e0-8d3ebb2938fd.png)
