### ISSUE TITLE
Error con el modulo en opencart 2.2

### ISSUE THREAD

**Issue by Pheader** [mercadopago/cart-opencart#80]
Hola. Estoy intentando probar el modulo de Mercadopago en opencart. Al ver que no es compatible aun con la version 2.3 y luego de varios intentos decidi probar en la version 2.2. 

Se instala correctamente y puedo configurarla ok. Pero al momento de probar alguna compra me figura internet server error. 

Alguien tiene alguna sugerencia al respecto? Gracias!

**Comment by prodos8** [comment]
lo mismo sucede en Opencart 2.1.0.1, la ultima version de MercadoPago Standard Checkout al intentar ir al checkout se muestra un mensaje de javascript "Internal server error"
En la consola de errores se muestra:
GET index.php?route=checkout/confirm 500 (Internal Server Error)

Por favor revisar esto

**Comment by flaviofat** [comment]
Olá a todos! Esta disponível a nova versão do mercado pago para o OpenCart 2.3. Por favor acesse o link abaixo para obter esta nova versão:

Hello everyone! The new version of the paid market for OpenCart 2.3 is available. Please go to the link below to get this new version:

¡Hola a todos! Esta disponible la nueva versión de mercado pago por OpenCart 2.3. Por favor visite el siguiente enlace para esta nueva versión:

https://github.com/mercadopago/cart-opencart

**Comment by diegolupinacci** [comment]
Tengo la versión 2.1 y me pasa lo mismo, tengo error cuando se selecciona el método de pago en el checkout.
Hay alguna solución o se sabe cuál es el problema?

Gracias
