### ISSUE TITLE
Error al configurar mercadopago como metodo de pago

### ISSUE THREAD

**Issue by IvoFacundo** [mercadopago/cart-opencart#82]
en la parte superior de la pagina en la que tengo que configurar mercadopago me sale este error

**Warning: Invalid argument supplied for foreach() in D:\xampp\htdocs\tienda\admin\controller\payment\mp_standard.php on line 114**

NO me deja elegir categoria y cuando doy al boton guardar no hace nada.

Alguna ayuda por favor!!

**Comment by flaviofat** [comment]
Olá a todos! Esta disponível a nova versão do mercado pago para o OpenCart 2.3. Por favor acesse o link abaixo para obter esta nova versão:

Hello everyone! The new version of the paid market for OpenCart 2.3 is available. Please go to the link below to get this new version:

¡Hola a todos! Esta disponible la nueva versión de mercado pago por OpenCart 2.3. Por favor visite el siguiente enlace para esta nueva versión:

https://github.com/mercadopago/cart-opencart
