### ISSUE TITLE
É possível clicar várias vezes em pagar no Checkout transparente (OC 2.2)

### ISSUE THREAD

**Issue by rdmegna** [mercadopago/cart-opencart#96]
Ao clicar em "Pagar", o botão "Pagar" continua habilitado, sem fornecer ao usuário qualquer feedback que o pedido está sendo feito. 
O botão de pagamento deveria ser desabilitado e deveria haver algum feedback que o usuário deve aguardar uma resposta.

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)
