### ISSUE TITLE
Error en el proceso de pago

### ISSUE THREAD

**Issue by josensanchez** [mercadopago/cart-opencart#98]
![error pago](https://user-images.githubusercontent.com/5849818/28835935-7eb91360-76bd-11e7-9e56-c963f6b651c5.jpg)

Este error lo tira en el proceso de pago.

Cambiaron la API?

cuando estiman que van a aplicar los cambios al plugin de opencart?

**Comment by josensanchez** [comment]
Cambios así en la API que nos dejan mal parado frente a los clientes.

cuando pueden tener una versión actualizada?

**Comment by flaviofat** [comment]
Liberamos novos plugins para Opencart com correções (Se possivel baixar a versão mais recente de Opencart 3.x)

Liberamos nuevos plugins para Opencart con correcciones (si es posible descargar la versión más reciente de Opencart 3.x)
